[package]
name = "geli"
version = "0.1.0"
edition = "2021"

[dependencies]
# Handles powerful command-line argument parsing
clap = { version = "4.4", features = ["derive"] }

# Handles reading and writing your local .geli.json files
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
yaml-rust2 = "0.13.0"

